### ISSUE TITLE
Cryptic error message

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/metaconfig#11]
```
[info]   ...
[info]   Cause: java.lang.IllegalArgumentException: Error reading field 'patches'. Expected argument of type PatchConfig. Obtained Failed to read class 'PatchConfig'
[info]   at metaconfig.Metaconfig$.get(Metaconfig.scala:33)
[info]   at scalafix.config.ScalafixConfig$$anon$1.read(ScalafixConfig.scala:18)
[info]   at scalafix.config.ScalafixConfig$$anonfun$gimmeClass$1.apply(ScalafixConfig.scala:38)
[info]   at scalafix.config.ScalafixConfig$$anonfun$gimmeClass$1.apply(ScalafixConfig.scala:38)
[info]   at scala.util.Either$RightProjection.flatMap(Either.scala:522)
[info]   at scalafix.config.ScalafixConfig$.gimmeClass(ScalafixConfig.scala:38)
[info]   at scalafix.config.ScalafixConfig$.fromString(ScalafixConfig.scala:40)
[info]   at scalafix.testkit.DiffTest$.scalafix$testkit$DiffTest$$apply(DiffTest.scala:66)
[info]   at scalafix.testkit.DiffTest$$anonfun$1.apply(DiffTest.scala:41)
[info]   at scalafix.testkit.DiffTest$$anonfun$1.apply(DiffTest.scala:38)
[info]   ...
[info]   Cause: java.lang.IllegalArgumentException: Failed to read class 'PatchConfig'
[info]   at scalafix.config.PatchConfig$$anon$1.read(PatchConfig.scala:18)
[info]   at metaconfig.Metaconfig$.get(Metaconfig.scala:20)
[info]   at scalafix.config.ScalafixConfig$$anon$1.read(ScalafixConfig.scala:18)
[info]   at scalafix.config.ScalafixConfig$$anonfun$gimmeClass$1.apply(ScalafixConfig.scala:38)
[info]   at scalafix.config.ScalafixConfig$$anonfun$gimmeClass$1.apply(ScalafixConfig.scala:38)
[info]   at scala.util.Either$RightProjection.flatMap(Either.scala:522)
[info]   at scalafix.config.ScalafixConfig$.gimmeClass(ScalafixConfig.scala:38)
[info]   at scalafix.config.ScalafixConfig$.fromString(ScalafixConfig.scala:40)
[info]   at scalafix.testkit.DiffTest$.scalafix$testkit$DiffTest$$apply(DiffTest.scala:66)
[info]   at scalafix.testkit.DiffTest$$anonfun$1.apply(DiffTest.scala:41)
[info]   ...
[info]   Cause: metaconfig.ConfigErrors: Failed to read class 'Replace'
[info]   at metaconfig.ConfDecoder$$anonfun$seqR$1.applyOrElse(ConfDecoder.scala:52)
[info]   at metaconfig.ConfDecoder$$anonfun$seqR$1.applyOrElse(ConfDecoder.scala:48)
[info]   at metaconfig.ConfDecoder$$anon$2.read(ConfDecoder.scala:34)
[info]   at scalafix.config.ScalafixMetaconfigReaders$$anonfun$listReader$1.applyOrElse(ScalafixMetaconfigReaders.scala:139)
[info]   at scalafix.config.ScalafixMetaconfigReaders$$anonfun$listReader$1.applyOrElse(ScalafixMetaconfigReaders.scala:136)
[info]   at metaconfig.ConfDecoder$$anon$2.read(ConfDecoder.scala:34)
[info]   at metaconfig.Metaconfig$.get(Metaconfig.scala:20)
[info]   at scalafix.config.PatchConfig$$anon$1.read(PatchConfig.scala:15)
[info]   at metaconfig.Metaconfig$.get(Metaconfig.scala:20)
[info]   at scalafix.config.ScalafixConfig$$anon$1.read(ScalafixConfig.scala:18)
```

in
```scala
patches.replacements = [ {
    from = _root_.scala.util.Right.
    to = 2 // expected string, was int
  }
  {
    from = "_root_.scala.Predef.String."
    to = "Int"
  }
  {
    from = _root_.scala.Int.
    to = String
  }
  {
    from = _root_.scala.util.Left.
    to = Right
}]
```

**Comment by olafurpg** [comment]
Fixed in 0.3.0 with a cleaned up ConfError api.
